trigger: none

pool: EXAMPLEPOOL

parameters:
  - name: HostPoolName
    type: string
    default: "AVD-TestHostpool"
    displayName: "Host Pool Name"

  - name: Location
    type: string
    default: "westeurope"
    displayName: "Location"

  - name: ResourceGroupName
    type: string
    default: "AVD-HostDevelopment-DEV_rg"
    displayName: "Resource Group Name"

  - name: HostPoolType
    type: string
    default: "Pooled"
    displayName: "Host Pool Type"
    values:
      - "Pooled"
      - "Personal"

  - name: LoadBalancerType
    type: string
    default: "BreadthFirst"
    displayName: "Load Balancer Type"
    values:
      - "BreadthFirst"
      - "DepthFirst"

  - name: PreferredAppGroupType
    type: string
    default: "Desktop"
    displayName: "Preferred App Group Type"
    values:
      - "Desktop"
      - "Application"

  - name: MaxSessionLimit
    type: number
    default: 10
    displayName: "Max Session Limit"

  - name: VMSize
    type: string
    default: "Standard_D2s_v3"
    displayName: "VM Size"

  - name: DiskSize
    type: number
    default: 128
    displayName: "Disk Size (GB)"

  - name: OS
    type: string
    default: "Windows11"
    displayName: "Operating System"
    values:
      - "Windows10"
      - "Windows11"

  - name: DeploymentEnvironment
    type: string
    default: "Dev"
    displayName: "Deployment Environment"
    values:
      - "Prod"
      - "Dev"

  - name: UserName
    type: string
    default: "adminuser"
    displayName: "AdminUserName"

  - name: Password
    type: string
    default: "ADMINPASSWORD"
    displayName: "Admin Password"

  - name: VmName
    type: string
    default: "VMNAME"
    displayName: "VM Name"

steps:
  - checkout: self

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: "AZURESUBSCRIPTION"
      ScriptPath: "PSScripts/Create-AVDHostPool.ps1"
      ScriptArguments: '-HostPoolName "$(HostPoolName)" -Location "$(Location)" -ResourceGroupName "$(ResourceGroupName)" -HostPoolType "$(HostPoolType)" -LoadBalancerType "$(LoadBalancerType)" -PreferredAppGroupType "$(PreferredAppGroupType)" -MaxSessionLimit "$(MaxSessionLimit)"'

      FailOnStandardError: true
      azurePowerShellVersion: "LatestVersion"

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: "AZURESUBSCRIPTION"
      ScriptPath: "PSScripts/Create-AVDVM.ps1"
      ScriptArguments: "-Location $(Location) -OS $(OS) -DeploymentEnvironment $(DeploymentEnvironment) -VMSize $(VMSize) -DiskSize $(DiskSize) -UserName $(UserName) -Password $(Password) -VirtualNetworkName $(VirtualNetworkName) -SubnetName $(SubnetName) -NetResourceGroupName $(NetResourceGroupName) -ResourceGroupName $(ResourceGroupName)"
      FailOnStandardError: true
      azurePowerShellVersion: "LatestVersion"

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: "AZURESUBSCRIPTION"
      ScriptPath: "PSScripts/Assign-VMToAVDHostPool.ps1"
      ScriptArguments: "-HostPoolName $(HostPoolName) -VmName $(VmName) -Location $(Location) -ResourceGroupName $(ResourceGroupName)"
      FailOnStandardError: true
      azurePowerShellVersion: "LatestVersion"
