---
name: Linting files
on:
  pull_request:
    branches: [dev]
env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit
  VALIDATE_ALL_CODEBASE: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DISABLE: COPYPASTE,SPELL
  DISABLE_LINTERS: TERRAFORM_TERRASCAN,REPOSITORY_TRUFFLEHOG,REPOSITORY_SECRETLINT
  CSHARP_DOTNET_FORMAT_ARGUMENTS: --no-restore
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: MegaLinter
        uses: megalinter/megalinter/flavors/dotnet@v7

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log

      - name: Prepare commit
        if: success() || failure()
        run: sudo chown -Rc $UID .git/

      - name: Commit and push applied linter fixes
        if: success() || failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: >-
            ${{
              github.event.pull_request.head.ref ||
              github.head_ref ||
              github.ref
            }}
          commit_message: "[MegaLinter] Apply linters fixes"
          commit_user_name: megalinter-bot
          commit_user_email: linting@xoap.io
